### PR TITLE
Add Roslyn version 3.3.0.1938114 binaries

### PR DESCRIPTION
**Pull request by radical**
..  from the vsix, corresponding to the nuget Microsoft.Net.Compilers 3.3.0-beta2-19381-14 .

- Removed these from the vsix:
	- [Content_Types].xml
	- catalog.json
	- extension.vsixmanifest
	- manifest.json
	- Roslyn.Compilers.Extension.* (windows/VS specific)
	- skipped package/* directory

- Edited `csi.rsp` with (matches what we used for 3.1.0):

```
-/r:System
-/r:System.Core
-/r:Microsoft.CSharp
+/r:System.dll
+/r:System.Core.dll
+/r:Microsoft.CSharp.dll
+/r:Facades/System.Runtime.dll
+/r:Facades/netstandard.dll
 /u:System
 /u:System.IO
 /u:System.Collections.Generic
```

- New files as compared to 3.1.0:
	- Microsoft.Managed.EditorConfig.targets

### CODE REVIEW

**Comment by radical** [comment]
msbuild side: https://github.com/mono/msbuild/pull/123

**Comment by akoeplinger** [comment]
We don't need the Roslyn.Compilers.Extension files, they are Windows/VS specific.

**Comment by radical** [comment]
@akoeplinger thanks, removed those files.

**Comment by radical** [comment]
@marek-safar Is this specific to 3.3.0? These files were present in the `3.1.0` dir too. I will remove them from `3.3.0`.

**Pull request merged**
