### PR TITLE
Replace DefaultInterfaceImplementation with Roslyn Compilers 3.1.0.19.10509

### PR DESCRIPTION
**Pull request by kg**
from https://dotnet.myget.org/feed/roslyn/package/vsix/7922692f-f018-45e7-8f3f-d3b7c0262841/3.1.0.1910509

### CODE REVIEW

**Comment by marek-safar** [comment]
Please remove the duplicate facades we already ship

**Comment by kg** [comment]
How do I determine which ones to remove? Just keep the set of files the same as before?

**Comment by kg** [comment]
Going to re-test a full build with this before we merge

**Comment by kg** [comment]
Doing this broke the build somehow.

**Pull request merged**
