### PR TITLE
Add Roslyn version 3.3.0-beta1-19327-03

### PR DESCRIPTION
**Pull request by agocke**

### CODE REVIEW

**Comment by radical** [comment]
I think it would be very useful to have some details in the commit message for the roslyn-binaries, like:

1. The commit hash and branch from which this nuget was generated
2. A changelog since the last version, autogenerated from the commit hashes is fine
3. If the contents being added here are exactly what the nuget has or were some files/assemblies skipped for some reason

This would help with reproducing, comparing, and debugging, IMHO.

**Comment by agocke** [comment]
That sounds useful. I'll log an issue in roslyn-tools to improve this behavior.

**Comment by agocke** [comment]
Long term though, if mono adopts Arcade and Maestro, this repository will be obsolete. How much effort do you want to put into these commits?

**Comment by lambdageek** [comment]
It's difficult to tell on the github website - is `latest` a symlink to `3.3.0-beta1-19327-03` or a second copy of all the files?

**Comment by agocke** [comment]
The purpose of this work is to update more frequently, so using major versions will not work anymore. Similarly, is there an automated way to know what's not necessary on mono?

**Pull request closed without merging**
